import { CandidateType } from "@/models/common";

export const SidebarLinks = [
  {
    icon: "/assets/Home.svg",
    title: "Scroll",
  },
  {
    icon: "/assets/Projects.svg",
    title: "Projects",
  },
  {
    icon: "/assets/Inbox.svg",
    title: "Inbox",
  },
  {
    icon: "/assets/Jobs.svg",
    title: "Jobs",
  },
  {
    icon: "/assets/Search.svg",
    title: "Search",
  },
  {
    icon: "/assets/Network.svg",
    title: "My Network",
  },
];

export const CandidatesColumnStyleConfig: Record<
  string,
  Record<string, string>
> = {
  rejected: {
    icon: "/assets/Rejected Icon.svg",
    bgColor: "#FFEAEA",
    color: "#EB5757",
    parentBorderColor: "#FFEAEA",
  },
  applied: {
    bgColor: "#E1E4E8",
    color: "#0D0D0D",
    parentBorderColor: "#E1E4E8",
  },
  shortlisted: {
    icon: "/assets/Accepted Icon.svg",
    bgColor: "#E2F5EA",
    color: "#219653",
    parentBorderColor: "#E2F5EA",
  },
};

export const Candidates: CandidateType[] = [
  {
    id: "1",
    name: "Ronald Richards",
    designation: "Cloud Consultant at Rapid Circle",
    status: "rejected",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: false,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "2",
    name: "Esther Howard",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "3",
    name: "Leslie Alexander",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "4",
    name: "Leslie Alexander",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "5",
    name: "Darrell Steward",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: false,
    notice_period: "30 days",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
    isExternal: true,
    resume: "DarrellSteward.pdf",
  },
  {
    id: "6",
    name: "Guy Hawkins",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "7",
    name: "Cody Fisher",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "8",
    name: "Dianne Russell",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "9",
    name: "Wade Warren",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "10",
    name: "Darrell Steward",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "11",
    name: "Ralph Edwards",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "12",
    name: "Marvin McKinney",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
    referrer: "Akash",
  },
  {
    id: "13",
    name: "Arlene McCoy",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    id: "14",
    name: "Bessie Cooper",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
    isMatched: true,
  },
];
