import { CandidateType } from "@/models/common";

export const SidebarLinks = [
  {
    icon: "/assets/Home.svg",
    title: "Scroll",
  },
  {
    icon: "/assets/Projects.svg",
    title: "Projects",
  },
  {
    icon: "/assets/Inbox.svg",
    title: "Inbox",
  },
  {
    icon: "/assets/Jobs.svg",
    title: "Jobs",
  },
  {
    icon: "/assets/Search.svg",
    title: "Search",
  },
  {
    icon: "/assets/Network.svg",
    title: "My Network",
  },
];

export const CandidatesColumnStyleConfig: Record<
  string,
  Record<string, string>
> = {
  rejected: {
    icon: "/assets/Rejected Icon.svg",
    bgColor: "#FFEAEA",
    color: "#EB5757",
    count: "1",
    parentBorderColor: "#FFEAEA",
  },
  applied: {
    bgColor: "#E1E4E8",
    color: "#0D0D0D",
    count: "142",
    parentBorderColor: "#E1E4E8",
  },
  shortlisted: {
    icon: "/assets/Accepted Icon.svg",
    bgColor: "#E2F5EA",
    color: "#219653",
    count: "24",
    parentBorderColor: "#E2F5EA",
  },
};

export const Candidates: CandidateType[] = [
  {
    name: "Ronald Richards",
    designation: "Cloud Consultant at Rapid Circle",
    status: "rejected",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: false,
    verified: true,
    notice_period: "immediate",
  },
  {
    name: "Esther Howard",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Leslie Alexander",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Leslie Alexander",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Darrell Steward",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: false,
    notice_period: "30 days",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
    isExternal: true,
    resume: "DarrellSteward.pdf",
  },
  {
    name: "Guy Hawkins",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Cody Fisher",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Dianne Russell",
    designation: "Cloud Consultant at Rapid Circle",
    status: "applied",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Wade Warren",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Darrell Steward",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Ralph Edwards",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Marvin McKinney",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Arlene McCoy",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
  },
  {
    name: "Bessie Cooper",
    designation: "Cloud Consultant at Rapid Circle",
    status: "shortlisted",
    last_updated: new Date(),
    applied_date: "1d",
    experience: "11y 6m",
    holding_offer: true,
    verified: true,
    notice_period: "immediate",
    email: "darrell.stewards@emaildomain.com",
    phone: "+1 12345 67490",
    isMatched: true,
  },
];
